spring.application.name=Rp-ecommerce

#configuration for database
spring.datasource.url =jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}

#jpa related configuration

spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.show-sql = true

server.port=8081

#datasource initialization
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

#setting up image folder
project.image=images

#Max size per file
spring.servlet.multipart.max-file-size=2MB
#max size per request
spring.servlet.multipart.max-request-size=10MB

# jwt related configuration

spring.app.secretKey=${JWT_SECRETKEY}
spring.app.jwtExpirationMs=864000000
spring.app.jwtCookieName=Rp-ecommerceCookie

#logging related configuration
#stripe related configuration
stripe.api.key=${STRIPE_SK}
stripe.publishable.key=${STRIPE_PK}